### ISSUE TITLE
Colors in vtk visualizations are not correct

### ISSUE THREAD

**Issue by aseeland** [VirtualProgrammingLab/viplab-vue-frontend#17]
At the moment the 3d visualizations show only a red cube that never gets visually updated.
It is unclear why.

The code for the vue-component has been transferred from https://git.iws.uni-stuttgart.de/dumux-repositories/dumux-web-app/-/tree/master/services/client/react-frontend/src/components/VTKViewer where it is working

**Comment by aseeland** [comment]
Sarbani found out that it is not an update-problem. Instead it is incorrect right from the beginning, regardless of the data range in the file being visualized. Maybe a problem in the itk-conversion-step?

**Comment by Sarbani-Roy** [comment]
I guess the problem is in the reading of VTU files. I am trying to write a _reader_ for a small example.

**Comment by aseeland** [comment]
@pascalseeland I think we can close this, right?
